---
title: "Title page"
author: Tormey Reimer
date: last-modified
---

This page serves as an overall table of contents for all the project documentation. 

# Data extraction and prep

These scripts extract and tidy raw data for use further down the line. Where possible, the data is extract from its rawest possible form 

These scripts take available data (`data\raw_data`) and prepare it for use in this analysis (`data\prepped_data`). Where possible, the incoming data is in its raw, publicly available form (i.e. downloaded straight from the source). These scripts were run prior to completing the analysis below and do not need to be re-run when replicating the analysis - the data produced from the following scripts is available on request.

| Script | Dataset |
|:-------------------|:----------------------------------------------------------------|
| [historical-sst.R](data-prep-scripts/historical-sst.R) | GHRSST, 0.25 degree resolution, MUR L4 analysis [@nasajpl_ghrsst_2015; @nasajpl_ghrsst_2019] |
| [aquaculture-production-data.R](data-prep-scripts\aquaculture-production-data.R) | FAO aquaculture production data [@fao_fishstat_2026] |
| [mariculture-locations.R](data-prep-scripts\mariculture-locations.R) | Aquaculture siting maps [@clawson_mapping_2022; @clawson_mapping_2022_data] |

# Analysis

These scripts run the actual processes and analysis for the project, using the data prepared by the script above. These markdowns must be run in order as they rely on data generated by previous scripts and markdowns.

| Script | Description |
|:--------------------------------|:---------------------------------------------------------|
| [00_model_function_demonstration.qmd](documentation-qmds/00_model_function_demonstration.html) | A demonstration of the basic bioenergetic model functions, outputs, and some useful wrappers. |
| [01_choosing_species.qmd](documentation-qmds/01_choosing_species.html) | Identifies the top 25 most-produced fed marine and brackishwater aquaculture species using FAO data from 2011 onwards, ranked by cumulative production volume. Includes production trends over time and an assessment of how much of global aquaculture production the top 25 species collectively represent. |
| [02_01_check_species_european_seabass.qmd](02_01_check_species_european_seabass.html) | |
| [04_assigning_locations.qmd](documentation-qmds/04_assigning_locations.html) | Assigns farm locations to each model name according to previously-mapped locations, or habitat suitability if mapped locations are missing. |


