---
title: "Tidying raw data"
author: 
  - Tormey Reimer
  - Richard Cottrell
date: today
---

# Introduction



```{r setup, include=F, cache=F}
library(tidyverse)
library(here)
library(terra)
library(qs)

here("src") %>% 
  list.files(pattern = "\\.R$", full.names = TRUE) %>% 
  walk(source)
```

# Mariculture locations

Pull in mariculture locations data from Clawson et al (2022) and save the species groups of interest.

```{r locations}
#code-summary: Read in farm locations and save for salmonids only

farm_locations <- file.path(bigdata_path, "all_marine_aquaculture_farms_sources_final.csv") %>% 
  read.csv() %>% 
  mutate(tonnes_per_farm = set_units(tonnes_per_farm)) %>% 
  filter(species_group == "Salmonidae fish") %>% 
  select(-c(details, data_type_2, data_source, data_type, data_year))

qsave(farm_locations, file.path(input_farm_coords_path, "salmon_marine_farm_locations.qs"))
```

# Vulnerability

Pull in spp vulnerability to eutrophication data - save to salmon folder.

```{r}
vuln_scores <- file.path(bigdata_path, "butt_spp_vuln_framework-publication/_output/vuln_gapfilled_score.csv") %>% 
  read.csv() %>% 
  select(vuln_gf_id, eutrophication_nutrient_pollution)

vuln_sd <- file.path(bigdata_path, "butt_spp_vuln_framework-publication/_output/vuln_gapfilled_sd.csv") %>% 
  read.csv() %>% 
  select(vuln_gf_id, eutrophication_nutrient_pollution) %>% 
  rename(sd = eutrophication_nutrient_pollution)

vuln_tx <- file.path(bigdata_path, "butt_spp_vuln_framework-publication/_output/vuln_gapfilled_tx.csv") %>% 
  read.csv()

full_vuln_df <- 
  vuln_scores %>% 
  left_join(vuln_sd) %>% 
  left_join(vuln_tx)

qsave(full_vuln_df, here("data/_general_data/species_layers/vulnerabilities/marine_spp_vulnerabilities_eutrophication.qs"))
```

# Distribution

Pull in spp distribution data from Aquamaps

```{r}
aquamaps_0.5d <- data.table::fread(file.path(rdsi_data_dir, "aquamaps/aquamaps_0.6_depth_prepped.csv")) 

#all cells have an id. These id's can be used to isolate only the cells of relevance for the salmon farming locations.
filter(aquamaps_0.5d, is.na(cell_id))

#save to project
qsave(x = aquamaps_0.5d, file = here("data/_general_data/species_layers/distribution/aquamaps_0.5d.qs"))
```
